// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: balls_info.proto

#ifndef PROTOBUF_balls_5finfo_2eproto__INCLUDED
#define PROTOBUF_balls_5finfo_2eproto__INCLUDED

#include <string>

#include <google/protobuf/stubs/common.h>

#if GOOGLE_PROTOBUF_VERSION < 2004000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please update
#error your headers.
#endif
#if 2004001 < GOOGLE_PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers.  Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/repeated_field.h>
#include <google/protobuf/extension_set.h>
#include <google/protobuf/generated_message_reflection.h>
// @@protoc_insertion_point(includes)

// Internal implementation detail -- do not call these.
void  protobuf_AddDesc_balls_5finfo_2eproto();
void protobuf_AssignDesc_balls_5finfo_2eproto();
void protobuf_ShutdownFile_balls_5finfo_2eproto();

class BallInfo;
class BallsInfo;
class CreateBall;
class RemoveBall;
class RemoveBalls;
class MoveBall;

// ===================================================================

class BallInfo : public ::google::protobuf::Message {
 public:
  BallInfo();
  virtual ~BallInfo();
  
  BallInfo(const BallInfo& from);
  
  inline BallInfo& operator=(const BallInfo& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const BallInfo& default_instance();
  
  void Swap(BallInfo* other);
  
  // implements Message ----------------------------------------------
  
  BallInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BallInfo& from);
  void MergeFrom(const BallInfo& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 sock = 1;
  inline bool has_sock() const;
  inline void clear_sock();
  static const int kSockFieldNumber = 1;
  inline ::google::protobuf::int32 sock() const;
  inline void set_sock(::google::protobuf::int32 value);
  
  // optional int32 id = 2;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 2;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);
  
  // optional double r = 3;
  inline bool has_r() const;
  inline void clear_r();
  static const int kRFieldNumber = 3;
  inline double r() const;
  inline void set_r(double value);
  
  // optional double x = 4;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 4;
  inline double x() const;
  inline void set_x(double value);
  
  // optional double y = 5;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 5;
  inline double y() const;
  inline void set_y(double value);
  
  // @@protoc_insertion_point(class_scope:BallInfo)
 private:
  inline void set_has_sock();
  inline void clear_has_sock();
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_r();
  inline void clear_has_r();
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 sock_;
  ::google::protobuf::int32 id_;
  double r_;
  double x_;
  double y_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(5 + 31) / 32];
  
  friend void  protobuf_AddDesc_balls_5finfo_2eproto();
  friend void protobuf_AssignDesc_balls_5finfo_2eproto();
  friend void protobuf_ShutdownFile_balls_5finfo_2eproto();
  
  void InitAsDefaultInstance();
  static BallInfo* default_instance_;
};
// -------------------------------------------------------------------

class BallsInfo : public ::google::protobuf::Message {
 public:
  BallsInfo();
  virtual ~BallsInfo();
  
  BallsInfo(const BallsInfo& from);
  
  inline BallsInfo& operator=(const BallsInfo& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const BallsInfo& default_instance();
  
  void Swap(BallsInfo* other);
  
  // implements Message ----------------------------------------------
  
  BallsInfo* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const BallsInfo& from);
  void MergeFrom(const BallsInfo& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated .BallInfo ball = 1;
  inline int ball_size() const;
  inline void clear_ball();
  static const int kBallFieldNumber = 1;
  inline const ::BallInfo& ball(int index) const;
  inline ::BallInfo* mutable_ball(int index);
  inline ::BallInfo* add_ball();
  inline const ::google::protobuf::RepeatedPtrField< ::BallInfo >&
      ball() const;
  inline ::google::protobuf::RepeatedPtrField< ::BallInfo >*
      mutable_ball();
  
  // @@protoc_insertion_point(class_scope:BallsInfo)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::BallInfo > ball_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_balls_5finfo_2eproto();
  friend void protobuf_AssignDesc_balls_5finfo_2eproto();
  friend void protobuf_ShutdownFile_balls_5finfo_2eproto();
  
  void InitAsDefaultInstance();
  static BallsInfo* default_instance_;
};
// -------------------------------------------------------------------

class CreateBall : public ::google::protobuf::Message {
 public:
  CreateBall();
  virtual ~CreateBall();
  
  CreateBall(const CreateBall& from);
  
  inline CreateBall& operator=(const CreateBall& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const CreateBall& default_instance();
  
  void Swap(CreateBall* other);
  
  // implements Message ----------------------------------------------
  
  CreateBall* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const CreateBall& from);
  void MergeFrom(const CreateBall& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 id = 1;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 1;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);
  
  // optional double x = 2;
  inline bool has_x() const;
  inline void clear_x();
  static const int kXFieldNumber = 2;
  inline double x() const;
  inline void set_x(double value);
  
  // optional double y = 3;
  inline bool has_y() const;
  inline void clear_y();
  static const int kYFieldNumber = 3;
  inline double y() const;
  inline void set_y(double value);
  
  // @@protoc_insertion_point(class_scope:CreateBall)
 private:
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_x();
  inline void clear_has_x();
  inline void set_has_y();
  inline void clear_has_y();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  double x_;
  double y_;
  ::google::protobuf::int32 id_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(3 + 31) / 32];
  
  friend void  protobuf_AddDesc_balls_5finfo_2eproto();
  friend void protobuf_AssignDesc_balls_5finfo_2eproto();
  friend void protobuf_ShutdownFile_balls_5finfo_2eproto();
  
  void InitAsDefaultInstance();
  static CreateBall* default_instance_;
};
// -------------------------------------------------------------------

class RemoveBall : public ::google::protobuf::Message {
 public:
  RemoveBall();
  virtual ~RemoveBall();
  
  RemoveBall(const RemoveBall& from);
  
  inline RemoveBall& operator=(const RemoveBall& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const RemoveBall& default_instance();
  
  void Swap(RemoveBall* other);
  
  // implements Message ----------------------------------------------
  
  RemoveBall* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RemoveBall& from);
  void MergeFrom(const RemoveBall& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 sock = 1;
  inline bool has_sock() const;
  inline void clear_sock();
  static const int kSockFieldNumber = 1;
  inline ::google::protobuf::int32 sock() const;
  inline void set_sock(::google::protobuf::int32 value);
  
  // optional int32 id = 2;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 2;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);
  
  // @@protoc_insertion_point(class_scope:RemoveBall)
 private:
  inline void set_has_sock();
  inline void clear_has_sock();
  inline void set_has_id();
  inline void clear_has_id();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 sock_;
  ::google::protobuf::int32 id_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(2 + 31) / 32];
  
  friend void  protobuf_AddDesc_balls_5finfo_2eproto();
  friend void protobuf_AssignDesc_balls_5finfo_2eproto();
  friend void protobuf_ShutdownFile_balls_5finfo_2eproto();
  
  void InitAsDefaultInstance();
  static RemoveBall* default_instance_;
};
// -------------------------------------------------------------------

class RemoveBalls : public ::google::protobuf::Message {
 public:
  RemoveBalls();
  virtual ~RemoveBalls();
  
  RemoveBalls(const RemoveBalls& from);
  
  inline RemoveBalls& operator=(const RemoveBalls& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const RemoveBalls& default_instance();
  
  void Swap(RemoveBalls* other);
  
  // implements Message ----------------------------------------------
  
  RemoveBalls* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const RemoveBalls& from);
  void MergeFrom(const RemoveBalls& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // repeated .RemoveBall rm_ball = 1;
  inline int rm_ball_size() const;
  inline void clear_rm_ball();
  static const int kRmBallFieldNumber = 1;
  inline const ::RemoveBall& rm_ball(int index) const;
  inline ::RemoveBall* mutable_rm_ball(int index);
  inline ::RemoveBall* add_rm_ball();
  inline const ::google::protobuf::RepeatedPtrField< ::RemoveBall >&
      rm_ball() const;
  inline ::google::protobuf::RepeatedPtrField< ::RemoveBall >*
      mutable_rm_ball();
  
  // @@protoc_insertion_point(class_scope:RemoveBalls)
 private:
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::RepeatedPtrField< ::RemoveBall > rm_ball_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(1 + 31) / 32];
  
  friend void  protobuf_AddDesc_balls_5finfo_2eproto();
  friend void protobuf_AssignDesc_balls_5finfo_2eproto();
  friend void protobuf_ShutdownFile_balls_5finfo_2eproto();
  
  void InitAsDefaultInstance();
  static RemoveBalls* default_instance_;
};
// -------------------------------------------------------------------

class MoveBall : public ::google::protobuf::Message {
 public:
  MoveBall();
  virtual ~MoveBall();
  
  MoveBall(const MoveBall& from);
  
  inline MoveBall& operator=(const MoveBall& from) {
    CopyFrom(from);
    return *this;
  }
  
  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _unknown_fields_;
  }
  
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return &_unknown_fields_;
  }
  
  static const ::google::protobuf::Descriptor* descriptor();
  static const MoveBall& default_instance();
  
  void Swap(MoveBall* other);
  
  // implements Message ----------------------------------------------
  
  MoveBall* New() const;
  void CopyFrom(const ::google::protobuf::Message& from);
  void MergeFrom(const ::google::protobuf::Message& from);
  void CopyFrom(const MoveBall& from);
  void MergeFrom(const MoveBall& from);
  void Clear();
  bool IsInitialized() const;
  
  int ByteSize() const;
  bool MergePartialFromCodedStream(
      ::google::protobuf::io::CodedInputStream* input);
  void SerializeWithCachedSizes(
      ::google::protobuf::io::CodedOutputStream* output) const;
  ::google::protobuf::uint8* SerializeWithCachedSizesToArray(::google::protobuf::uint8* output) const;
  int GetCachedSize() const { return _cached_size_; }
  private:
  void SharedCtor();
  void SharedDtor();
  void SetCachedSize(int size) const;
  public:
  
  ::google::protobuf::Metadata GetMetadata() const;
  
  // nested types ----------------------------------------------------
  
  // accessors -------------------------------------------------------
  
  // optional int32 sock = 1;
  inline bool has_sock() const;
  inline void clear_sock();
  static const int kSockFieldNumber = 1;
  inline ::google::protobuf::int32 sock() const;
  inline void set_sock(::google::protobuf::int32 value);
  
  // optional int32 id = 2;
  inline bool has_id() const;
  inline void clear_id();
  static const int kIdFieldNumber = 2;
  inline ::google::protobuf::int32 id() const;
  inline void set_id(::google::protobuf::int32 value);
  
  // optional double v_val = 3;
  inline bool has_v_val() const;
  inline void clear_v_val();
  static const int kVValFieldNumber = 3;
  inline double v_val() const;
  inline void set_v_val(double value);
  
  // optional double v_dir = 4;
  inline bool has_v_dir() const;
  inline void clear_v_dir();
  static const int kVDirFieldNumber = 4;
  inline double v_dir() const;
  inline void set_v_dir(double value);
  
  // @@protoc_insertion_point(class_scope:MoveBall)
 private:
  inline void set_has_sock();
  inline void clear_has_sock();
  inline void set_has_id();
  inline void clear_has_id();
  inline void set_has_v_val();
  inline void clear_has_v_val();
  inline void set_has_v_dir();
  inline void clear_has_v_dir();
  
  ::google::protobuf::UnknownFieldSet _unknown_fields_;
  
  ::google::protobuf::int32 sock_;
  ::google::protobuf::int32 id_;
  double v_val_;
  double v_dir_;
  
  mutable int _cached_size_;
  ::google::protobuf::uint32 _has_bits_[(4 + 31) / 32];
  
  friend void  protobuf_AddDesc_balls_5finfo_2eproto();
  friend void protobuf_AssignDesc_balls_5finfo_2eproto();
  friend void protobuf_ShutdownFile_balls_5finfo_2eproto();
  
  void InitAsDefaultInstance();
  static MoveBall* default_instance_;
};
// ===================================================================


// ===================================================================

// BallInfo

// optional int32 sock = 1;
inline bool BallInfo::has_sock() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void BallInfo::set_has_sock() {
  _has_bits_[0] |= 0x00000001u;
}
inline void BallInfo::clear_has_sock() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void BallInfo::clear_sock() {
  sock_ = 0;
  clear_has_sock();
}
inline ::google::protobuf::int32 BallInfo::sock() const {
  return sock_;
}
inline void BallInfo::set_sock(::google::protobuf::int32 value) {
  set_has_sock();
  sock_ = value;
}

// optional int32 id = 2;
inline bool BallInfo::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void BallInfo::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void BallInfo::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void BallInfo::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 BallInfo::id() const {
  return id_;
}
inline void BallInfo::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// optional double r = 3;
inline bool BallInfo::has_r() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void BallInfo::set_has_r() {
  _has_bits_[0] |= 0x00000004u;
}
inline void BallInfo::clear_has_r() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void BallInfo::clear_r() {
  r_ = 0;
  clear_has_r();
}
inline double BallInfo::r() const {
  return r_;
}
inline void BallInfo::set_r(double value) {
  set_has_r();
  r_ = value;
}

// optional double x = 4;
inline bool BallInfo::has_x() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void BallInfo::set_has_x() {
  _has_bits_[0] |= 0x00000008u;
}
inline void BallInfo::clear_has_x() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void BallInfo::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline double BallInfo::x() const {
  return x_;
}
inline void BallInfo::set_x(double value) {
  set_has_x();
  x_ = value;
}

// optional double y = 5;
inline bool BallInfo::has_y() const {
  return (_has_bits_[0] & 0x00000010u) != 0;
}
inline void BallInfo::set_has_y() {
  _has_bits_[0] |= 0x00000010u;
}
inline void BallInfo::clear_has_y() {
  _has_bits_[0] &= ~0x00000010u;
}
inline void BallInfo::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline double BallInfo::y() const {
  return y_;
}
inline void BallInfo::set_y(double value) {
  set_has_y();
  y_ = value;
}

// -------------------------------------------------------------------

// BallsInfo

// repeated .BallInfo ball = 1;
inline int BallsInfo::ball_size() const {
  return ball_.size();
}
inline void BallsInfo::clear_ball() {
  ball_.Clear();
}
inline const ::BallInfo& BallsInfo::ball(int index) const {
  return ball_.Get(index);
}
inline ::BallInfo* BallsInfo::mutable_ball(int index) {
  return ball_.Mutable(index);
}
inline ::BallInfo* BallsInfo::add_ball() {
  return ball_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::BallInfo >&
BallsInfo::ball() const {
  return ball_;
}
inline ::google::protobuf::RepeatedPtrField< ::BallInfo >*
BallsInfo::mutable_ball() {
  return &ball_;
}

// -------------------------------------------------------------------

// CreateBall

// optional int32 id = 1;
inline bool CreateBall::has_id() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void CreateBall::set_has_id() {
  _has_bits_[0] |= 0x00000001u;
}
inline void CreateBall::clear_has_id() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void CreateBall::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 CreateBall::id() const {
  return id_;
}
inline void CreateBall::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// optional double x = 2;
inline bool CreateBall::has_x() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void CreateBall::set_has_x() {
  _has_bits_[0] |= 0x00000002u;
}
inline void CreateBall::clear_has_x() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void CreateBall::clear_x() {
  x_ = 0;
  clear_has_x();
}
inline double CreateBall::x() const {
  return x_;
}
inline void CreateBall::set_x(double value) {
  set_has_x();
  x_ = value;
}

// optional double y = 3;
inline bool CreateBall::has_y() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void CreateBall::set_has_y() {
  _has_bits_[0] |= 0x00000004u;
}
inline void CreateBall::clear_has_y() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void CreateBall::clear_y() {
  y_ = 0;
  clear_has_y();
}
inline double CreateBall::y() const {
  return y_;
}
inline void CreateBall::set_y(double value) {
  set_has_y();
  y_ = value;
}

// -------------------------------------------------------------------

// RemoveBall

// optional int32 sock = 1;
inline bool RemoveBall::has_sock() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void RemoveBall::set_has_sock() {
  _has_bits_[0] |= 0x00000001u;
}
inline void RemoveBall::clear_has_sock() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void RemoveBall::clear_sock() {
  sock_ = 0;
  clear_has_sock();
}
inline ::google::protobuf::int32 RemoveBall::sock() const {
  return sock_;
}
inline void RemoveBall::set_sock(::google::protobuf::int32 value) {
  set_has_sock();
  sock_ = value;
}

// optional int32 id = 2;
inline bool RemoveBall::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void RemoveBall::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void RemoveBall::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void RemoveBall::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 RemoveBall::id() const {
  return id_;
}
inline void RemoveBall::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// -------------------------------------------------------------------

// RemoveBalls

// repeated .RemoveBall rm_ball = 1;
inline int RemoveBalls::rm_ball_size() const {
  return rm_ball_.size();
}
inline void RemoveBalls::clear_rm_ball() {
  rm_ball_.Clear();
}
inline const ::RemoveBall& RemoveBalls::rm_ball(int index) const {
  return rm_ball_.Get(index);
}
inline ::RemoveBall* RemoveBalls::mutable_rm_ball(int index) {
  return rm_ball_.Mutable(index);
}
inline ::RemoveBall* RemoveBalls::add_rm_ball() {
  return rm_ball_.Add();
}
inline const ::google::protobuf::RepeatedPtrField< ::RemoveBall >&
RemoveBalls::rm_ball() const {
  return rm_ball_;
}
inline ::google::protobuf::RepeatedPtrField< ::RemoveBall >*
RemoveBalls::mutable_rm_ball() {
  return &rm_ball_;
}

// -------------------------------------------------------------------

// MoveBall

// optional int32 sock = 1;
inline bool MoveBall::has_sock() const {
  return (_has_bits_[0] & 0x00000001u) != 0;
}
inline void MoveBall::set_has_sock() {
  _has_bits_[0] |= 0x00000001u;
}
inline void MoveBall::clear_has_sock() {
  _has_bits_[0] &= ~0x00000001u;
}
inline void MoveBall::clear_sock() {
  sock_ = 0;
  clear_has_sock();
}
inline ::google::protobuf::int32 MoveBall::sock() const {
  return sock_;
}
inline void MoveBall::set_sock(::google::protobuf::int32 value) {
  set_has_sock();
  sock_ = value;
}

// optional int32 id = 2;
inline bool MoveBall::has_id() const {
  return (_has_bits_[0] & 0x00000002u) != 0;
}
inline void MoveBall::set_has_id() {
  _has_bits_[0] |= 0x00000002u;
}
inline void MoveBall::clear_has_id() {
  _has_bits_[0] &= ~0x00000002u;
}
inline void MoveBall::clear_id() {
  id_ = 0;
  clear_has_id();
}
inline ::google::protobuf::int32 MoveBall::id() const {
  return id_;
}
inline void MoveBall::set_id(::google::protobuf::int32 value) {
  set_has_id();
  id_ = value;
}

// optional double v_val = 3;
inline bool MoveBall::has_v_val() const {
  return (_has_bits_[0] & 0x00000004u) != 0;
}
inline void MoveBall::set_has_v_val() {
  _has_bits_[0] |= 0x00000004u;
}
inline void MoveBall::clear_has_v_val() {
  _has_bits_[0] &= ~0x00000004u;
}
inline void MoveBall::clear_v_val() {
  v_val_ = 0;
  clear_has_v_val();
}
inline double MoveBall::v_val() const {
  return v_val_;
}
inline void MoveBall::set_v_val(double value) {
  set_has_v_val();
  v_val_ = value;
}

// optional double v_dir = 4;
inline bool MoveBall::has_v_dir() const {
  return (_has_bits_[0] & 0x00000008u) != 0;
}
inline void MoveBall::set_has_v_dir() {
  _has_bits_[0] |= 0x00000008u;
}
inline void MoveBall::clear_has_v_dir() {
  _has_bits_[0] &= ~0x00000008u;
}
inline void MoveBall::clear_v_dir() {
  v_dir_ = 0;
  clear_has_v_dir();
}
inline double MoveBall::v_dir() const {
  return v_dir_;
}
inline void MoveBall::set_v_dir(double value) {
  set_has_v_dir();
  v_dir_ = value;
}


// @@protoc_insertion_point(namespace_scope)

#ifndef SWIG
namespace google {
namespace protobuf {


}  // namespace google
}  // namespace protobuf
#endif  // SWIG

// @@protoc_insertion_point(global_scope)

#endif  // PROTOBUF_balls_5finfo_2eproto__INCLUDED
